@baseUrl = https://localhost:7196

@partId = b7c47513-1018-42c6-a559-0619e7deb0a5
@empId = eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee
@repairTaskId = aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
@customerId = f1111111-1111-1111-1111-111111111111
@customerId2 = f2222222-2222-2222-2222-222222222222
@workOrderId = 0d4e9484-de67-47dd-a2b0-08894c42847e

// Part ===============================================
GET {{baseUrl}}/api/parts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3OC0xMjM0LTEyMzQtMTIzNC0xMjM0NTY3OCIsImVtYWlsIjoiYUBnbWFpbC5jb20iLCJyb2xlIjoiTWFuYWdlciIsIm5iZiI6MTc3MTk1MjAwMSwiZXhwIjoxNzcxOTUzODAxLCJpYXQiOjE3NzE5NTIwMDEsImlzcyI6ImxvY2FsaG9zdCIsImF1ZCI6ImxvY2FsaG9zdCJ9.tEjMu0gQuk3TLju4KQL8hVSLmx1WMNHqhuTgBwVU9tc

###
GET {{baseUrl}}/api/parts/{{partId}}

###
POST {{baseUrl}}/api/parts
Content-type: application/json

{
  "Name" : "merdfggdfgdfgdfgo",
  "Cost" : 100,
  "Quantity" : 10
}

###
PUT {{baseUrl}}/api/parts/{{partId}}
Content-type: application/json

{
  "Name" : "UpdatedPart",
  "Cost" : 999.99,
  "Quantity" : 100
}

###
DELETE {{baseUrl}}/api/parts/{{partId}}



// Employee ===============================================
###
GET {{baseUrl}}/api/employees

###
GET {{baseUrl}}/api/employees/{{empId}}

###
POST {{baseUrl}}/api/employees
Content-type: application/json

{
  "firstName": "Ameer2",
  "lastName": "TamimTamiTamimi2Tamimi2mi2Tamimi2Tamimi2Tamimi2Tamimi2Tamimi2Tamimi2Tamimi2Tamimi2Tamimi2i2",
  "role": "Manager"
}

###
PUT {{baseUrl}}/api/employees/{{empId}}
Content-type: application/json

{
    "firstName": "aa",
    "lastName": "bbbb",
    "fullName": "Yousef Amir",
    "role": "Labor2"
}

###
DELETE {{baseUrl}}/api/employees/4d488fd3-b34c-44fe-a6fc-4fa65d9774ae


// Identity ===============================================

###
POST {{baseUrl}}/api/identity
Content-type: application/json

{
  "Email" : "a@gmail.com",
  "Password" : "a@gmail.com"
}

###
POST {{baseUrl}}/api/identity/refresh-token
Content-type: application/json

{
  "Token" : "0K1rEJtrqeZpiCdAKPk5kQ7pop8PldpYXvOVkQWUNLI="
}

======================== Repair Tasks
###
GET {{baseUrl}}/api/repairTasks

###
GET {{baseUrl}}/api/repairTasks/{{repairTaskId}}

###
POST {{baseUrl}}/api/repairTasks
Content-type: application/json

{
  "name": "Window Fix1111111",
  "description": "We wont ruin it this time :)",
  "timeEstimated": 10,
  "costEstimated": 4000,
  "parts": [
    {
      "partId": "b7c47513-1018-42c6-a559-0619e7deb0a5",
      "quantity": 3
    },
    {
      "partId": "57bdd1fb-8345-4282-aa37-3c9b046aeb47",
      "quantity": 1
    }
  ]
}

###
PUT {{baseUrl}}/api/repairTasks/{{repairTaskId}}
Content-type: application/json

{
  "name": "Battery Repair11111",
  "description": "We wont ruin it this time :)",
  "timeEstimated": 45,
  "costEstimated": 1500,
  "parts": [
    {
      "partId": "b7c47513-1018-42c6-a559-0619e7deb0a5",
      "quantity": 1
    },
    {
      "partId": "7d7c1cc2-ff4c-4301-9e7b-493e1519e22d",
      "quantity" : 2
    }
  ]
}

###
DELETE {{baseUrl}}/api/repairTasks/ea9b3577-c72f-46f4-b452-bab9a6473120


// Customers ===============================================

###
GET {{baseUrl}}/api/customers


###
GET {{baseUrl}}/api/customers/f2222222-2222-2222-2222-222222222222

###
POST {{baseUrl}}/api/customers
Content-type: application/json

{
  "firstName": "Mohammad",
  "lastName": "Hassan",
  "phone": "0591234567",
  "email": "mohammad.hassan@gmail.com",
  "address": "Nablus - Rafidia",
  "vehicles": [
    {
      "brand": "Toyota",
      "model": "Corolla",
      "year": 2018,
      "licensePlate": "NAP-123145"
    },
    {
      "brand": "Hyundai",
      "model": "Elantra",
      "year": 2020,
      "licensePlate": "NAP-617890"
    }
  ]
}

###
PUT {{baseUrl}}/api/customers/f1111111-1111-1111-1111-111111111111
Content-type: application/json

 {
    "firstName": "Mohammad",
    "lastName": "Hassan3",
    "phone": "0591234567",
    "email": "mohammad.hassan@gmail.com",
    "address": "Nablus - Rafidia",
    "vehicles": [
      {
        "id": "2d13b9e1-6a50-4e35-9af3-29bc6b1a9be3",
        "customerId": "f1111111-1111-1111-1111-111111111111",
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2018,
        "licensePlate": "NAP-12345",
        "vehicleInfo": "Toyota | Corolla | 2018"
      },
      {
        "id": "22ad247a-e053-4348-ba2e-9bb818681899",
        "customerId": "f1111111-1111-1111-1111-111111111111",
        "brand": "Hyundai",
        "model": "Elantra",
        "year": 2020,
        "licensePlate": "NAP-67890",
        "vehicleInfo": "Hyundai | Elantra | 2020"
      }
    ]
  }

###
DELETE {{baseUrl}}/api/customers/8f605e85-440c-4f9e-9268-529d08b833fd


// Work Orders ===================================================

###
GET {{baseUrl}}/api/workorders?State=Completed1

###
GET {{baseUrl}}/api/workorders/0d4e9484-de67-47dd-a2b0-08894c42847e

###
POST {{baseUrl}}/api/workorders
Content-type: application/json

{
    "vehicleId": "2d13b9e1-6a50-4e35-9af3-29bc6b1a9be3",
    "customerId": "f1111111-1111-1111-1111-111111111111",
    "employeeId": "dddddddd-dddd-dddd-dddd-dddddddddddd",
    "startTime": "2026-03-07T12:22:09.6730816",
    "bay" : "B",
    "WorkOrderRepairTasks": [
      {
        "RepairTaskId": "c3e88507-9013-4b96-bad8-796f09434820"
      }
    ]
 }

###
DELETE {{baseUrl}}/api/workorders/eb35a655-cdc3-4675-adaa-cd5ab8b506cc


###
PUT {{baseUrl}}/api/workorders/technician/99999999-9999-9999-9999-999999999991
Content-type: application/json

{
    "employeeId" : "{{empId}}"
}

###
PUT {{baseUrl}}/api/workorders/state/{{workOrderId}}
Content-type: application/json

{
    "state" : "InProgress"
}

###
PUT {{baseUrl}}/api/workorders/relocate/{{workOrderId}}
Content-type: application/json

{
    "startTime" : "2026-03-04T21:22:00.6730816",
    "bay" : "A"
}

### 
PUT {{baseUrl}}/api/workorders/vehicle/{{workOrderId}}
Content-type: application/json

{
    "vehicleId" : "2d13b9e1-6a50-4e35-9af3-29bc6b1a9be3"
}

### 
PUT {{baseUrl}}/api/workorders/repair-tasks/{{workOrderId}}
Content-type: application/json

{
    "WorkOrderRepairTasks" : [
      {"RepairTaskId" : "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"},
      {"RepairTaskId" : "c3e88507-9013-4b96-bad8-796f09434820"}
    ]
}

###
GET {{baseUrl}}/api/workorders/schedule
Content-type: application/json

{
  "Day" : "2026-03-04"
}

###
GET {{baseUrl}}/api/workorders/technician-schedule
Content-type: application/json

{
  "EmployeeId" : "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
  "Day" : "2026-03-01"
}